# Generated by Django 5.0.3 on 2024-04-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_network_tool_game_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.AlterField(
            model_name='game',
            name='network',
            field=models.IntegerField(),
        ),
    ]
