# Generated by Django 5.0.3 on 2024-04-01 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_player_age_alter_game_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='round_payoff',
            new_name='payoff',
        ),
        migrations.AddField(
            model_name='round',
            name='robustness',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
