# Generated by Django 5.0.3 on 2024-04-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_round_payoff_round_payoff_round_robustness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='tool',
            field=models.IntegerField(),
        ),
    ]
