# Generated by Django 5.0.3 on 2024-04-01 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_round_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='chosen_node',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='payoff',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='robustness',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
