# Generated by Django 5.0.3 on 2024-04-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_round_id_alter_round_round_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='isEnd',
            field=models.BooleanField(default=False),
        ),
    ]
