# Generated by Django 5.0.3 on 2024-04-01 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_round_isend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='isEnd',
            new_name='is_end',
        ),
    ]
