# Generated by Django 5.0.3 on 2024-04-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_isend_round_is_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='robustness',
        ),
        migrations.AlterField(
            model_name='round',
            name='chosen_node',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
