# Generated by Django 5.0.3 on 2024-04-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_round_robustness_alter_round_chosen_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='chosen_node',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
